### ISSUE TITLE
Receiving "You need to specify either `text` or `text_target`."

### ISSUE THREAD

**Issue by ckrogers1us** [alpertunga-bile/image-caption-comfyui#3]
I have tried and received the same error with both my ComfyUI_windows_portable and C:\StabilityMatrix instances.  I'm using the referenced image.

![Capture](https://github.com/user-attachments/assets/d1efdff0-d441-400a-a2b7-2fdce380b602)

Error occurred when executing Image Caption Node:

You need to specify either `text` or `text_target`.

File "C:\StabilityMatrix\Packages\ComfyUI\execution.py", line 317, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "C:\StabilityMatrix\Packages\ComfyUI\execution.py", line 192, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "C:\StabilityMatrix\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
process_inputs(input_dict, i)
File "C:\StabilityMatrix\Packages\ComfyUI\execution.py", line 158, in process_inputs
results.append(getattr(obj, func)(**inputs))
File "C:\StabilityMatrix\Packages\ComfyUI\custom_nodes\image-caption-comfyui\image_caption.py", line 151, in image_caption
inputs = processor(images=img, return_tensors="pt").to(dev)
File "C:\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 3049, in __call__
raise ValueError("You need to specify either `text` or `text_target`.")

**Comment by alpertunga-bile** [comment]
Hello @ckrogers1us, thanks for reporting. I did a clean setup for ComfyUI and the node. As I understand from your image, you are using the provided pretrained model which's name endswith "_blip". So I used the model and it seems working:

![image](https://github.com/user-attachments/assets/ea80e436-c97d-4a91-bdfc-d598ffd37af1)

Can you check your transformers package version? I tested it with 4.44.2 version.

## Check Version for Manual Installation

- Activate the virtual environment if there is one.
- Run the below command:
```bash
pip show transformers
```

## Check Version for Portable Installation

- Go to ```ComfyUI_windows_portable``` folder.
- Open the terminal here.
- Run the below command:
```bash
.\python_embeded\python.exe -s -m pip show transformers
```

**Comment by ckrogers1us** [comment]
![Capture](https://github.com/user-attachments/assets/ecb3c5de-7b18-41aa-8434-58900c5c299a)
I do have the 4.44.2 transformers package version.  I have discovered my error.  This only works with the female_image_caption_blip or the female_image_caption_git models.  I was trying to use the female_positive_generator_v5.  There is no issue with the Node.  Thank you for looking into my error.

**Comment by alpertunga-bile** [comment]
No problem. Glad your issue is solved.
